"use client";
import { FormEvent, useEffect, useState } from "react";
import { CatNote, catsApi, NoteInput } from "@/lib/api";
import { CatProfileSectionHeader } from "@/components/cat-profile-section-header";
import { ApiErrorHandler, formatDate } from "@/lib/utils";
const emptyNote = (): NoteInput => ({ date: new Date().toISOString().slice(0, 10), comment: "" });
export function CatNotes({ catId, onChanged }: { catId: string; onChanged?: () => Promise<void> }) {
  const [notes, setNotes] = useState<CatNote[]>([]); const [form, setForm] = useState<NoteInput>(emptyNote); const [editingId, setEditingId] = useState<string | null>(null); const [expanded, setExpanded] = useState(false); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [actionId, setActionId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = async () => setNotes(await catsApi.listNotes(catId));
  useEffect(() => { let cancelled = false; catsApi.listNotes(catId).then((items) => { if (!cancelled) setNotes(items); }).catch((reason: unknown) => { if (!cancelled) setError(ApiErrorHandler.handle(reason)); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [catId]);
  const reset = () => { setEditingId(null); setForm(emptyNote()); setFormOpen(false); setError(null); };
  const add = () => { setEditingId(null); setForm(emptyNote()); setError(null); setFormOpen(true); setExpanded(true); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!form.date || !form.comment.trim()) { setError("Enter a date and comment."); return; } setSaving(true); setError(null); try { const payload = { ...form, comment: form.comment.trim() }; if (editingId) await catsApi.updateNote(editingId, payload); else await catsApi.createNote(catId, payload); await refresh(); await onChanged?.(); reset(); } catch (reason) { setError(ApiErrorHandler.handle(reason)); } finally { setSaving(false); } };
  const edit = (note: CatNote) => { setEditingId(note.id); setForm({ date: note.date, comment: note.comment }); setFormOpen(true); setExpanded(true); };
  const remove = async (id: string) => { setActionId(id); setError(null); try { await catsApi.deleteNote(id); await refresh(); await onChanged?.(); if (editingId === id) reset(); } catch (reason) { setError(ApiErrorHandler.handle(reason)); } finally { setActionId(null); } };
  return <section className="overflow-hidden md:col-span-2 rounded-[22px] border border-[#d4c7b4] bg-[#fff8ee]/85 p-6 shadow-panel backdrop-blur-sm"><CatProfileSectionHeader title="Notes" isExpanded={expanded} onToggle={() => { if (expanded) reset(); setExpanded((value) => !value); }} onAdd={add} addLabel="Add note" />{expanded && <>{formOpen && <form onSubmit={submit} className="mt-3 grid gap-3 rounded-xl border border-[#d4c7b4] bg-white/50 p-4"><label className="grid gap-1 text-sm font-medium text-gray-800"><span>Date <span className="text-red-700">*</span></span><input aria-label="Note date" type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} className="rounded-lg border border-[#d4c7b4] bg-white px-3 py-2" /></label><label className="grid gap-1 text-sm font-medium text-gray-800"><span>Comment <span className="text-red-700">*</span></span><textarea aria-label="Note comment" value={form.comment} onChange={(event) => setForm({ ...form, comment: event.target.value })} rows={3} className="resize-y rounded-lg border border-[#d4c7b4] bg-white px-3 py-2" /></label><div className="flex gap-2"><button disabled={saving} className="rounded-xl bg-[#d05a2c] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save"}</button><button type="button" onClick={reset} className="rounded-xl border border-[#d4c7b4] px-4 py-2 text-sm font-semibold">Cancel</button></div></form>}{error && <p className="mt-3 text-sm font-medium text-red-700">{error}</p>}{loading && <p className="mt-4 text-sm text-[#6d6a66]">Loading notes...</p>}{!loading && notes.length === 0 && <p className="mt-4 rounded-xl border border-dashed border-[#d4c7b4] p-4 text-sm text-[#6d6a66]">No notes yet.</p>}<ol className="mt-4 space-y-3">{notes.map((note) => <li key={note.id} className="flex items-start justify-between gap-3 rounded-xl border border-[#d4c7b4] bg-white/60 p-4"><div><time className="font-mono text-xs uppercase tracking-[0.1em] text-[#6d6a66]">{formatDate(note.date)}</time><p className="mt-1 whitespace-pre-wrap break-words text-gray-900">{note.comment}</p></div><div className="flex shrink-0 gap-1"><button type="button" onClick={() => edit(note)} aria-label="Edit note" title="Edit note" className="rounded-lg p-2 text-amber-700 hover:bg-amber-100">вњЋ</button><button type="button" disabled={actionId === note.id} onClick={() => void remove(note.id)} aria-label="Delete note" title="Delete note" className="rounded-lg p-2 text-red-700 hover:bg-red-100 disabled:opacity-50">рџ—‘</button></div></li>)}</ol></>}</section>;
}
