ALTER TABLE "CatPhoto" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CatTag" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CatAuditEvent" ADD COLUMN "tagId" TEXT;
CREATE INDEX "CatAuditEvent_tagId_idx" ON "CatAuditEvent"("tagId");
ALTER TABLE "CatAuditEvent" ADD CONSTRAINT "CatAuditEvent_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "CatTag"("id") ON DELETE SET NULL ON UPDATE CASCADE;
